"""empty message

Revision ID: 1657b7b69274
Revises:
Create Date: 2024-10-31 18:12:47.579233

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1657b7b69274"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_spimex_trading_results_id", table_name="spimex_trading_results")
    op.drop_table("spimex_trading_results")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spimex_trading_results",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "exchange_product_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "exchange_product_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("oil_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "delivery_basis_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivery_basis_name", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "delivery_type_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("volume", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("total", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_on", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="spimex_trading_results_pkey"),
        sa.UniqueConstraint(
            "exchange_product_id", name="spimex_trading_results_exchange_product_id_key"
        ),
    )
    op.create_index(
        "ix_spimex_trading_results_id", "spimex_trading_results", ["id"], unique=False
    )
    # ### end Alembic commands ###
